# -*- coding: utf-8 -*-
"""food.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkvfa-tFutF2CQolL0q2awpvVQuehtwY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## For one Person"""

# Load the CSV files
annotations = pd.read_csv(r".\1101\1101_annotate.csv")
sensor_data = pd.read_csv(r".\1101\1101_sensorData.csv")

# Convert Unix time to a human-readable format
annotations['timestamp'] = pd.to_datetime(annotations['unix time'], unit='ms')
sensor_data['timestamp'] = pd.to_datetime(sensor_data['Unix Time'], unit='ms')

sensor_data

# Removing light sensor data no use

sensor_data = sensor_data[sensor_data['Sensor'] != 'LTR-506ALS Light sensor']
print(sensor_data)

# Assuming sensor_data and annotations DataFrames are already defined
numeric_columns = ['Value1', 'Value2', 'Value3']
sensor_data_resampled = (sensor_data
    .set_index('timestamp')
    .groupby('Sensor')[numeric_columns]
    .resample('200ms')
    .mean()
    .reset_index()
)

# Sort both DataFrames by timestamp
sensor_data_resampled = sensor_data_resampled.sort_values('timestamp')
annotations = annotations.sort_values('timestamp')

# Merge with annotations using nearest merge
sensor_data_aligned = pd.merge_asof(
    sensor_data_resampled,
    annotations[['timestamp', 'Activity', 'Status']],
    on='timestamp',
    direction='nearest'
)
# print(sensor_data_aligned)
# Interpolate missing sensor data to fill gaps
sensor_data_aligned.interpolate(method='linear', inplace=True)

# Display the first few rows of the aligned data
print(sensor_data_aligned)

sensor_data_aligned.to_csv(r".\1101\1101_sensor_data_aligned.csv", index=False, header=True, encoding='utf-8')

"""Exploratory Data Analysis"""

sensor_data_aligned['norm2'] = np.sqrt(
    sensor_data_aligned['Value1']**2 +
    sensor_data_aligned['Value2']**2 +
    sensor_data_aligned['Value3']**2
)

sensor_data_aligned.to_csv(r".\1101\1101_sensor_data_aligned.csv", index=False, header=True, encoding='utf-8')
# saving norm2

# Display basic statistics
print(sensor_data_aligned.describe())

from scipy import stats
from scipy.fft import fft
from scipy.stats import skew, kurtosis

"""### Window size = 5 sec"""

# Define window size (in seconds)
window_size = 5

# Create a column for window assignment based on the window size
sensor_data_aligned['window'] = (sensor_data_aligned['timestamp'] - sensor_data_aligned['timestamp'].min()) // pd.Timedelta(seconds=window_size)

# Function to extract statistical features
def extract_features(group):
    features = {}
    # For each axis (Value1, Value2, Value3)
    for axis in ['Value1','Value2','Value3']:
        axis_data = group[axis]
        features[f'{axis}_mean'] = axis_data.mean()
        features[f'{axis}_variance'] = axis_data.var()
        features[f'{axis}_skewness'] = skew(axis_data)
        features[f'{axis}_kurtosis'] = kurtosis(axis_data)
        features[f'{axis}_intensity'] = np.sum(axis_data ** 2)
    return pd.Series(features)

# Apply feature extraction to each window and sensor
windowed_features = sensor_data_aligned.groupby(['window', 'Sensor']).apply(extract_features).reset_index()

# Pivot the table to get features as columns for each sensor
features_pivot = windowed_features.pivot(index='window', columns='Sensor').fillna(0)
features_pivot.columns = ['_'.join(col).strip() for col in features_pivot.columns.values]

print(features_pivot.describe())

# Function to assign the most frequent activity as the label for each window
def assign_label(group):
    return group['Activity'].mode()[0]  # Assign the most frequent activity in the window

# Assign labels based on the most frequent activity in each window
labels = sensor_data_aligned.groupby('window').apply(assign_label).reset_index(name='Activity')

# Combine the feature matrix with the labels
final_dataset = pd.merge(features_pivot, labels, on='window')
# Save the dataset to a CSV file
final_dataset.to_csv(r".\1101\1101_y.csv", index=False, header=True, encoding='utf-8')

# Add binary target column for 'eat'
final_dataset['target'] = final_dataset['Activity'].apply(lambda x: 1 if x == 'eat' else 0)

final_dataset.describe()

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Separate features and binary target
X = final_dataset.drop(columns=['window', 'Activity', 'target'])
y = final_dataset['target']

# Normalize the features using MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

X_train.shape

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Train logistic regression model
logistic_model = LogisticRegression(max_iter=1000, random_state=42)
logistic_model.fit(X_train, y_train)

# Make predictions on test data
y_pred_logistic = logistic_model.predict(X_test)

# Performance measures
print("Logistic Regression Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_logistic):.4f}")
print(classification_report(y_test, y_pred_logistic))

from sklearn.tree import DecisionTreeClassifier

# Train decision tree model
tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(X_train, y_train)

# Make predictions on test data
y_pred_tree = tree_model.predict(X_test)

# Performance measures
print("Decision Tree Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_tree):.4f}")
print(classification_report(y_test, y_pred_tree))

from sklearn.ensemble import RandomForestClassifier

# Train random forest model
forest_model = RandomForestClassifier(n_estimators=100, random_state=42)
forest_model.fit(X_train, y_train)

# Make predictions on test data
y_pred_forest = forest_model.predict(X_test)

# Performance measures
print("Random Forest Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_forest):.4f}")
print(classification_report(y_test, y_pred_forest))

from sklearn.svm import SVC

# Train SVM model
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)

# Make predictions on test data
y_pred_svm = svm_model.predict(X_test)

# Performance measures
print("SVM Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm):.4f}")
print(classification_report(y_test, y_pred_svm))

"""### Window size = 2 sec"""

# Define window size (in seconds)
window_size = 2  # You can adjust this to 10 if needed

# Create a column for window assignment based on the window size
sensor_data_aligned2 = sensor_data_aligned
sensor_data_aligned2['window'] = (sensor_data_aligned2['timestamp'] - sensor_data_aligned2['timestamp'].min()) // pd.Timedelta(seconds=window_size)

# Function to extract statistical features
def extract_features(group):
    features = {}
    # For each axis (Value1, Value2, Value3)
    for axis in ['Value1','Value2','Value3']:
        axis_data = group[axis]
        features[f'{axis}_mean'] = axis_data.mean()
        features[f'{axis}_variance'] = axis_data.var()
        features[f'{axis}_skewness'] = skew(axis_data)
        features[f'{axis}_kurtosis'] = kurtosis(axis_data)
        features[f'{axis}_intensity'] = np.sum(axis_data ** 2)
    return pd.Series(features)

# Apply feature extraction to each window and sensor
windowed_features2 = sensor_data_aligned2.groupby(['window', 'Sensor']).apply(extract_features).reset_index()

# Pivot the table to get features as columns for each sensor
features_pivot2 = windowed_features2.pivot(index='window', columns='Sensor').fillna(0)
features_pivot2.columns = ['_'.join(col).strip() for col in features_pivot2.columns.values]

features_pivot2.describe()

# Function to assign the most frequent activity as the label for each window
def assign_label(group):
    return group['Activity'].mode()[0]  # Assign the most frequent activity in the window

# Assign labels based on the most frequent activity in each window
labels = sensor_data_aligned2.groupby('window').apply(assign_label).reset_index(name='Activity')

# Combine the feature matrix with the labels
final_dataset2 = pd.merge(features_pivot2, labels, on='window')
# Save the dataset to a CSV file
# final_dataset.to_csv(r".\1101\1101_y.csv", index=False, header=True, encoding='utf-8')

final_dataset2['target'] = final_dataset2['Activity'].apply(lambda x: 1 if x == 'eat' else 0)

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Separate features and binary target
X = final_dataset2.drop(columns=['window', 'Activity', 'target'])
y = final_dataset2['target']

# Normalize the features using MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

X_train.shape

"""Model training"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Train logistic regression model
logistic_model = LogisticRegression(max_iter=1000, random_state=42)
logistic_model.fit(X_train, y_train)

# Make predictions on test data
y_pred_logistic = logistic_model.predict(X_test)

# Performance measures
print("Logistic Regression Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_logistic):.4f}")
print(classification_report(y_test, y_pred_logistic))

from sklearn.tree import DecisionTreeClassifier

# Train decision tree model
tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(X_train, y_train)

# Make predictions on test data
y_pred_tree = tree_model.predict(X_test)

# Performance measures
print("Decision Tree Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_tree):.4f}")
print(classification_report(y_test, y_pred_tree))

from sklearn.ensemble import RandomForestClassifier

# Train random forest model
forest_model = RandomForestClassifier(n_estimators=100, random_state=42)
forest_model.fit(X_train, y_train)

# Make predictions on test data
y_pred_forest = forest_model.predict(X_test)

# Performance measures
print("Random Forest Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_forest):.4f}")
print(classification_report(y_test, y_pred_forest))

from sklearn.svm import SVC

# Train SVM model
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)

# Make predictions on test data
y_pred_svm = svm_model.predict(X_test)

# Performance measures
print("SVM Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm):.4f}")
print(classification_report(y_test, y_pred_svm))

# Import the necessary libraries
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import numpy as np

# Prepare data (Assuming final_dataset is your dataset with features and target)
X = final_dataset.drop(columns=['window', 'Activity', 'target'])
y = final_dataset['target']  # Target column (1: eat, 0: not eat)

# Normalize the data using Min-Max Scaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print(X_train.shape)
# Apply SMOTE to oversample the minority class
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

# Check the class distribution after SMOTE
print(f'Class distribution after SMOTE: {dict(zip(*np.unique(y_resampled, return_counts=True)))}')

# Initialize models
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'SVM': SVC(random_state=42)
}

# Train and evaluate each model
for model_name, model in models.items():
    print(f"\nTraining {model_name}...")
    model.fit(X_resampled, y_resampled)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Evaluate performance
    print(f"{model_name} Results:")
    print(classification_report(y_test, y_pred, target_names=['Not Eat', 'Eat']))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

# Define window size (in seconds)
window_size = 5  # You can adjust this to 10 if needed

# Create a column for window assignment based on the window size
sensor_data_aligned['window'] = (sensor_data_aligned['timestamp'] - sensor_data_aligned['timestamp'].min()) // pd.Timedelta(seconds=window_size)

"""## Cummulative"""

import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Define numeric columns and window size
numeric_columns = ['Value1', 'Value2', 'Value3']
window_size = 5  # in seconds

# Placeholder to store data from all participants
cumulative_dataset = pd.DataFrame()

# Loop through each participant's data (IDs 1101 to 1138)
for person_id in range(1101, 1139):
    try:
        # Load the CSV files for the current person
        annotations_path = f"./{person_id}/{person_id}_annotate.csv"
        sensor_data_path = f"./{person_id}/{person_id}_sensorData.csv"

        annotations = pd.read_csv(annotations_path)
        sensor_data = pd.read_csv(sensor_data_path)

        # Convert timestamps to datetime
        annotations['timestamp'] = pd.to_datetime(annotations['unix time'], unit='ms')
        sensor_data['timestamp'] = pd.to_datetime(sensor_data['Unix Time'], unit='ms')

        # Filter out unwanted sensor (e.g., Light sensor)
        sensor_data = sensor_data[sensor_data['Sensor'] != 'LTR-506ALS Light sensor']

        # Resample the sensor data to 200ms intervals and compute mean for each group
        sensor_data_resampled = (sensor_data
            .set_index('timestamp')
            .groupby('Sensor')[numeric_columns]
            .resample('200ms')
            .mean()
            .reset_index()
        )

        # Sort both DataFrames by timestamp
        sensor_data_resampled = sensor_data_resampled.sort_values('timestamp')
        annotations = annotations.sort_values('timestamp')

        # Merge sensor data with annotations using nearest merge
        sensor_data_aligned = pd.merge_asof(
            sensor_data_resampled,
            annotations[['timestamp', 'Activity', 'Status']],
            on='timestamp',
            direction='nearest'
        )

        # Ensure sensor data columns are numeric before interpolation
        sensor_data_aligned[numeric_columns] = sensor_data_aligned[numeric_columns].apply(pd.to_numeric, errors='coerce')

        # Interpolate missing sensor data to fill gaps only on numeric columns
        sensor_data_aligned[numeric_columns] = sensor_data_aligned[numeric_columns].interpolate(method='linear')

        # Create a column for window assignment based on the window size
        sensor_data_aligned['window'] = (sensor_data_aligned['timestamp'] - sensor_data_aligned['timestamp'].min()) // pd.Timedelta(seconds=window_size)

        # Function to extract statistical features from each window
        def extract_features(group):
            features = {}
            for axis in numeric_columns:
                axis_data = group[axis]
                features[f'{axis}_mean'] = axis_data.mean()
                features[f'{axis}_variance'] = axis_data.var()
                features[f'{axis}_skewness'] = skew(axis_data)
                features[f'{axis}_kurtosis'] = kurtosis(axis_data)
                features[f'{axis}_intensity'] = np.sum(axis_data ** 2)
            return pd.Series(features)

        # Group by window and sensor, applying feature extraction function to numeric columns only
        windowed_features = sensor_data_aligned.groupby(['window', 'Sensor'], group_keys=False).apply(
            lambda group: extract_features(group[numeric_columns])
        ).reset_index()

        # Pivot the table to get features as columns for each sensor
        features_pivot = windowed_features.pivot(index='window', columns='Sensor').fillna(0)
        features_pivot.columns = ['_'.join(col).strip() for col in features_pivot.columns.values]

        # Function to assign the most frequent activity as the label for each window
        def assign_label(group):
            return group['Activity'].mode()[0]  # Assign the most frequent activity in the window

        # Group by window and apply the label assignment, only passing the 'Activity' column
        labels = sensor_data_aligned.groupby('window', group_keys=False).apply(
            lambda group: assign_label(group[['Activity']])
        ).reset_index(name='Activity')

        # Combine the feature matrix with the labels
        final_dataset = pd.merge(features_pivot, labels, on='window')

        # Add binary target column for 'eat' (1 for 'eat', 0 for others)
        final_dataset['target'] = final_dataset['Activity'].apply(lambda x: 1 if x == 'eat' else 0)

        # Append the current person's data to the cumulative dataset
        cumulative_dataset = pd.concat([cumulative_dataset, final_dataset], ignore_index=True)

    except FileNotFoundError as e:
        print(f"Data for person {person_id} not found, skipping...")

# Save the final cumulative dataset to a CSV file (optional)
cumulative_dataset.to_csv("cumulative_dataset.csv", index=False)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Consolidate and unify activity labels
label_mapping = {
    'computer_work': 'computer',
    'play_cellphone': 'computer',
    'ipad_work': 'computer',
    'computer': 'computer',
    'study': 'study',
    'homework': 'study',
    'home_work': 'study'
}

# Load cumulative dataset
cumulative_dataset = pd.read_csv('cumulative_sensor_data.csv')

# Apply label mapping to unify the activities
cumulative_dataset['Activity'] = cumulative_dataset['Activity'].replace(label_mapping)

# Define the main activity categories
main_activities = {'computer', 'study', 'eat', 'talk', 'drink', 'walk', 'stair'}

# Map all other activities to "Others"
cumulative_dataset['Activity'] = cumulative_dataset['Activity'].apply(lambda x: x if x in main_activities else 'Others')

# Assign target labels for multi-class classification
label_encoder = LabelEncoder()
cumulative_dataset['target_label'] = label_encoder.fit_transform(cumulative_dataset['Activity'])

# Prepare features and target for training
X = cumulative_dataset.drop(columns=['Activity', 'target_label', 'window'])  # Remove non-feature columns
y = cumulative_dataset['target_label']

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize models
models = {
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'SVM': SVC(random_state=42)
}

# Train and evaluate each model
for model_name, model in models.items():
    print(f"\nTraining {model_name}...")
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Evaluate performance
    print(f"{model_name} Results:")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred, target_names=label_encoder.classes_, zero_division=1))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

cumulative_dataset.to_csv(r"./cumulative_sensor_data.csv", index=False, header=True, encoding='utf-8')

cumulative_dataset.shape

cumulative_dataset['target'].sum()

"""Binary Classifier(Eat vs Not Eat)"""

# Save the cumulative dataset to a CSV file (optional)
# cumulative_dataset.to_csv(r"./cumulative_sensor_data.csv", index=False, header=True, encoding='utf-8')

# Prepare the cumulative dataset for training
X = cumulative_dataset.drop(columns=['window', 'Activity', 'target'])
y = cumulative_dataset['target']

# Normalize the features using MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Split the cumulative dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Training models and evaluating them
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Initialize models
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'SVM': SVC(random_state=42)
}

# Train and evaluate each model
for model_name, model in models.items():
    print(f"\nTraining {model_name}...")
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Evaluate performance
    print(f"{model_name} Results:")
    print(classification_report(y_test, y_pred, target_names=['Not Eat', 'Eat']))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

"""Multi-label classifier"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Consolidate and unify activity labels
label_mapping = {
    'computer_work': 'computer',
    'play_cellphone': 'computer',
    'ipad_work': 'computer',
    'computer': 'computer',
    'study': 'study',
    'homework': 'study',
    'home_work': 'study'
}

# Load cumulative dataset
cumulative_dataset = pd.read_csv('cumulative_sensor_data.csv')

# Apply label mapping to unify the activities
cumulative_dataset['Activity'] = cumulative_dataset['Activity'].replace(label_mapping)

# Define the main activity categories
main_activities = {'computer', 'study', 'eat', 'talk', 'drink', 'walk', 'stair'}

# Map all other activities to "Others"
cumulative_dataset['Activity'] = cumulative_dataset['Activity'].apply(lambda x: x if x in main_activities else 'Others')

# Assign target labels for multi-class classification
label_encoder = LabelEncoder()
cumulative_dataset['target_label'] = label_encoder.fit_transform(cumulative_dataset['Activity'])

# Prepare features and target for training
X = cumulative_dataset.drop(columns=['Activity', 'target_label', 'window'])  # Remove non-feature columns
y = cumulative_dataset['target_label']

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize models
models = {
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'SVM': SVC(random_state=42)
}

# Train and evaluate each model
for model_name, model in models.items():
    print(f"\nTraining {model_name}...")
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Evaluate performance
    print(f"{model_name} Results:")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred, target_names=label_encoder.classes_, zero_division=1))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

"""Hyperparameter tuning Random Forest Classifier"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Define parameter grid for Random Forest
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

# Initialize Random Forest
rf = RandomForestClassifier(random_state=42)

# Initialize Grid Search with cross-validation
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Best parameters from Grid Search
best_rf = grid_search.best_estimator_

# Predict and evaluate
y_pred = best_rf.predict(X_test)
print("Optimized Random Forest Results:")
print("Best Parameters:", grid_search.best_params_)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""# Eating Episode Detection

## approach 1
"""

import pandas as pd
import numpy as np  # Import numpy to use np.array
from sklearn.preprocessing import LabelEncoder

# Load data
data = pd.read_csv('cumulative_sensor_data2.csv')

import pandas as pd

# Pivot the table to have sensor types as columns
pivoted_data = data.pivot_table(index=['timestamp', 'person_id', 'Activity'],
                                columns='Sensor',
                                values=['Value1', 'Value2', 'Value3'])

# Flatten multi-level column index
pivoted_data.columns = ['_'.join(col).strip() for col in pivoted_data.columns.values]
pivoted_data.reset_index(inplace=True)

# Set timestamp as index for resampling
pivoted_data['timestamp'] = pd.to_datetime(pivoted_data['timestamp'])
pivoted_data.set_index('timestamp', inplace=True)
print(pivoted_data.head())

#encode activity into numeric
label_mapping = {
    'computer_work': 'computer',
    'play_cellphone': 'computer',
    'ipad_work': 'computer',
    'computer': 'computer',
    'study': 'study',
    'homework': 'study',
    'home_work': 'study'
}


# Apply label mapping to unify the activities
pivoted_data['Activity'] = pivoted_data['Activity'].replace(label_mapping)

# Define the main activity categories
main_activities = {'computer', 'study', 'eat', 'talk', 'drink', 'walk', 'stair'}

# Map all other activities to "Others"
pivoted_data['Activity'] = pivoted_data['Activity'].apply(lambda x: x if x in main_activities else 'Others')

# Assign target labels for multi-class classification
label_encoder = LabelEncoder()
pivoted_data['target_label'] = label_encoder.fit_transform(pivoted_data['Activity'])

pivoted_data.head

# Resample and interpolate missing values
column_headers = pivoted_data.columns.tolist()

# List of columns to remove
columns_to_remove = ['timestamp', 'person_id', 'Activity']

# Remove columns using a list comprehension
column_headers = [col for col in column_headers if col not in columns_to_remove]

resampled_data = pivoted_data.groupby('person_id')[column_headers].resample('100ms').mean().interpolate()
resampled_data.columns

resampled_data.head()

# Parameters for segmentation
segment_length = 50  # Adjust based on needs and data frequency

# Generator for segmentation to avoid memory issues
def segment_generator(resampled_data, segment_length):
    for person_id, person_data in resampled_data.groupby('person_id'):
        for i in range(0, len(person_data) - segment_length, segment_length):
            segment = person_data.iloc[i:i + segment_length]
            yield segment.drop(columns=['target_label']).values, segment['target_label'].mode()[0]

# Process each segment one by one
segments = []
labels = []

for X_segment, y_label in segment_generator(resampled_data, segment_length):
    segments.append(X_segment)
    labels.append(y_label)

# Convert lists to numpy arrays
X = np.array(segments)
y = np.array(labels)

# Optionally: Save the data in memory-mapped files for even more efficient handling
X_memmap = np.memmap('X_segments.dat', dtype='float32', mode='w+', shape=(len(segments), segment_length, X.shape[2]))
y_memmap = np.memmap('y_labels.dat', dtype='int32', mode='w+', shape=(len(labels),))

# Save the segmented data to memmap arrays
X_memmap[:] = X
y_memmap[:] = y

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout, Flatten

# Define CNN-LSTM model
model = Sequential([
    Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X.shape[1], X.shape[2])),
    MaxPooling1D(pool_size=2),
    Dropout(0.3),
    LSTM(100, return_sequences=True),
    Dropout(0.3),
    Flatten(),
    Dense(100, activation='relu'),
    Dropout(0.3),
    Dense(len(label_encoder.classes_), activation='softmax')  # Number of activities as output
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Split into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Predict on test set
y_pred = model.predict(X_test)
y_pred_labels = np.argmax(y_pred, axis=1)

# Post-process predictions to find eating episodes
eating_episodes = []
current_episode = None

for i, label in enumerate(y_pred_labels):
    if label_encoder.inverse_transform([label])[0] == 'eat':
        if current_episode is None:
            current_episode = [i, i]
        else:
            current_episode[1] = i
    else:
        if current_episode is not None:
            eating_episodes.append(current_episode)
            current_episode = None

y_pred

from sklearn.metrics import classification_report

print(classification_report(y_test, np.argmax(model.predict(X_test), axis=1)))

import pandas as pd
import numpy as np  # Import numpy to use np.array
from sklearn.preprocessing import LabelEncoder

# Load data
data = pd.read_csv('cumulative_sensor_data.csv')

# Set timestamp as index for resampling
# pivoted_data['timestamp'] = pd.to_datetime(pivoted_data['timestamp'])
# pivoted_data.set_index('timestamp', inplace=True)
print(data.head())
pivoted_data = data

label_mapping = {
    'computer_work': 'computer',
    'play_cellphone': 'computer',
    'ipad_work': 'computer',
    'computer': 'computer',
    'study': 'study',
    'homework': 'study',
    'home_work': 'study'
}


# Apply label mapping to unify the activities
pivoted_data['Activity'] = pivoted_data['Activity'].replace(label_mapping)

# Define the main activity categories
main_activities = {'computer', 'study', 'eat', 'talk', 'drink', 'walk', 'stair'}

# Map all other activities to "Others"
pivoted_data['Activity'] = pivoted_data['Activity'].apply(lambda x: x if x in main_activities else 'Others')

# Assign target labels for multi-class classification
label_encoder = LabelEncoder()
pivoted_data['target_label'] = label_encoder.fit_transform(pivoted_data['Activity'])

pivoted_data.columns

segments = pivoted_data.drop(columns=['Activity', 'target', 'target_label']).values
labels = pivoted_data['target_label'].values

X = np.expand_dims(segments, axis=1)  # Add a dummy temporal dimension
y = labels

print(f"Shape of X: {X.shape}")  # (num_samples, 1, num_features)
print(f"Shape of y: {y.shape}")  # (num_samples,)

model = Sequential([
    Conv1D(filters=64, kernel_size=1, activation='relu', input_shape=(X.shape[1], X.shape[2])),
    MaxPooling1D(pool_size=1),
    Dropout(0.1),
    LSTM(200, return_sequences=False),  # Adjust return_sequences to False
    Dropout(0.1),
    Dense(200, activation='relu'),
    Dropout(0.1),
    Dense(len(np.unique(y)), activation='softmax')  # Output for number of classes
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

from sklearn.model_selection import train_test_split

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Evaluate
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_accuracy}")

"""## approach 2"""

import pandas as pd
import numpy as np  # Import numpy to use np.array
from sklearn.preprocessing import LabelEncoder

# Load data
data = pd.read_csv('cumulative_sensor_data2.csv')



# Filter for MPL Gyroscope and MPL Accelerometer
gyro_data = data[data['Sensor'] == 'MPL Gyroscope'][['timestamp', 'Value1', 'Value2', 'Value3', 'Activity', 'person_id']]
accel_data = data[data['Sensor'] == 'MPL Accelerometer'][['timestamp', 'Value1', 'Value2', 'Value3', 'Activity', 'person_id']]

accel_data.isna().sum()

label_mapping = {
    'computer_work': 'computer',
    'play_cellphone': 'computer',
    'ipad_work': 'computer',
    'computer': 'computer',
    'study': 'study',
    'homework': 'study',
    'home_work': 'study'
}


# Apply label mapping to unify the activities
gyro_data['Activity'] = gyro_data['Activity'].replace(label_mapping)
accel_data['Activity'] = accel_data['Activity'].replace(label_mapping)

# Define the main activity categories
main_activities = {'computer', 'study', 'eat', 'talk', 'drink', 'walk', 'stair'}

# Map all other activities to "Others"
gyro_data['Activity'] = gyro_data['Activity'].apply(lambda x: x if x in main_activities else 'Others')
accel_data['Activity'] = accel_data['Activity'].apply(lambda x: x if x in main_activities else 'Others')

# Assign target labels for multi-class classification
label_encoder = LabelEncoder()
gyro_data['Activity'] = label_encoder.fit_transform(gyro_data['Activity'])
accel_data['Activity'] = label_encoder.fit_transform(accel_data['Activity'])

gyro_data.to_csv(r"./gyro_data.csv", index=False, header=True, encoding='utf-8')
accel_data.to_csv(r"./accel_data.csv", index=False, header=True, encoding='utf-8')

accel_data = accel_data.iloc[:-1, :]

import numpy as np

segment_length = 50  # Number of timesteps per segment
gyro_segments = []
accel_segments = []
labels = []

for person_id, person_data in gyro_data.groupby('person_id'):
    for i in range(0, len(person_data) - segment_length, segment_length):
        gyro_segment = person_data.iloc[i:i + segment_length][['Value1', 'Value2', 'Value3']].values
        # Append segments if the labels are consistent within the segment
        label = person_data.iloc[i:i + segment_length]['Activity'].mode()[0]
        gyro_segments.append(gyro_segment)
        labels.append(label)

for person_id, person_data in accel_data.groupby('person_id'):
    for i in range(0, len(person_data) - segment_length, segment_length):
        accel_segment = person_data.iloc[i:i + segment_length][['Value1', 'Value2', 'Value3']].values
        # Append segments if the labels are consistent within the segment
        label = person_data.iloc[i:i + segment_length]['Activity'].mode()[0]
        accel_segments.append(accel_segment)

# Convert to numpy arrays
gyro_X = np.array(gyro_segments)
accel_X = np.array(accel_segments)
y = np.array(labels)

y

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, LSTM, Dense, Dropout, Flatten, concatenate

# Define the input shape
input_shape = (gyro_X.shape[1], gyro_X.shape[2])

# Gyroscope stream
gyro_input = Input(shape=input_shape)
gyro_x = Conv1D(filters=64, kernel_size=3, activation='relu')(gyro_input)
gyro_x = MaxPooling1D(pool_size=2)(gyro_x)
gyro_x = LSTM(50, return_sequences=False)(gyro_x)

# Accelerometer stream
accel_input = Input(shape=input_shape)
accel_x = Conv1D(filters=64, kernel_size=3, activation='relu')(accel_input)
accel_x = MaxPooling1D(pool_size=2)(accel_x)
accel_x = LSTM(50, return_sequences=False)(accel_x)

# Concatenate streams
combined = concatenate([gyro_x, accel_x])
x = Dense(100, activation='relu')(combined)
x = Dropout(0.3)(x)
output = Dense(len(label_encoder.classes_), activation='softmax')(x)

# Define the model
model = Model(inputs=[gyro_input, accel_input], outputs=output)

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

from sklearn.model_selection import train_test_split

# Split data into training and testing sets
gyro_X_train, gyro_X_test, accel_X_train, accel_X_test, y_train, y_test = train_test_split(
    gyro_X, accel_X, y, test_size=0.2, random_state=42
)

# Train the model
history = model.fit([gyro_X_train, accel_X_train], y_train, epochs=10, batch_size=32,
                    validation_data=([gyro_X_test, accel_X_test], y_test))

"""diff Segment lengths"""

import numpy as np

segment_length = 150  # Number of timesteps per segment
gyro_segments = []
accel_segments = []
labels = []

for person_id, person_data in gyro_data.groupby('person_id'):
    for i in range(0, len(person_data) - segment_length, segment_length):
        gyro_segment = person_data.iloc[i:i + segment_length][['Value1', 'Value2', 'Value3']].values
        # Append segments if the labels are consistent within the segment
        label = person_data.iloc[i:i + segment_length]['Activity'].mode()[0]
        gyro_segments.append(gyro_segment)
        labels.append(label)

for person_id, person_data in accel_data.groupby('person_id'):
    for i in range(0, len(person_data) - segment_length, segment_length):
        accel_segment = person_data.iloc[i:i + segment_length][['Value1', 'Value2', 'Value3']].values
        # Append segments if the labels are consistent within the segment
        label = person_data.iloc[i:i + segment_length]['Activity'].mode()[0]
        accel_segments.append(accel_segment)

# Convert to numpy arrays
gyro_X = np.array(gyro_segments)
accel_X = np.array(accel_segments)
y = np.array(labels)

from sklearn.model_selection import train_test_split

# Split data into training and testing sets
gyro_X_train, gyro_X_test, accel_X_train, accel_X_test, y_train, y_test = train_test_split(
    gyro_X, accel_X, y, test_size=0.2, random_state=42
)

# Train the model
history = model.fit([gyro_X_train, accel_X_train], y_train, epochs=10, batch_size=32,
                    validation_data=([gyro_X_test, accel_X_test], y_test))

"""## Bite analysis

"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(13, 8))

fig, axs = plt.subplots(1, 2, figsize=(30, 10), sharex='all', sharey='all')

# 300 rows = 60s interval
for activity in gyro_data.iloc[:300, :]['Activity'].unique():
    activity_data = gyro_data.iloc[:300, :][gyro_data.iloc[:300, :]['Activity'] == activity]

    sns.lineplot(x='timestamp', y='Value3', data=activity_data, ax=axs[0], label='z-axis')
    sns.lineplot(x='timestamp', y='Value2', data=activity_data, color = '#FFE4E1', ax = axs[0], label='y-axis')
    sns.lineplot(x='timestamp', y='Value1', data=activity_data, color = '#AFEEEE', ax = axs[0], label='x-axis')
    axs[0].set_title('Gyroscope sensor values')

    accel_activity_data = accel_data.iloc[:300, :][accel_data.iloc[:300, :]['Activity'] == activity]
    sns.lineplot(x='timestamp', y='Value3', data=accel_activity_data, ax=axs[1], label='z-axis')
    sns.lineplot(x='timestamp', y='Value2', data=accel_activity_data, color = '#FFE4E1', ax = axs[1], label='y-axis')
    sns.lineplot(x='timestamp', y='Value1', data=accel_activity_data, color = '#AFEEEE', ax = axs[1], label='x-axis')
    axs[1].set_title('Accelerometer sensor values')

for ax in axs:
    ax.legend(title='Sensor column')
plt.xlabel("Timestamp")
plt.ylabel("Sensor Values")

plt.legend(title="Activity")
plt.show()

# only z axis value seems relevant
plt.figure(figsize=(13, 8))

fig, axs = plt.subplots(1, 2, figsize=(30, 10), sharex='all', sharey='all')

# 300 rows = 60s interval
for activity in gyro_data.iloc[:300, :]['Activity'].unique():
    activity_data = gyro_data.iloc[:300, :][gyro_data.iloc[:300, :]['Activity'] == activity]

    sns.lineplot(x='timestamp', y='Value3', data=activity_data, ax=axs[0], label='z-axis')
    axs[0].axhline(y=20, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')

    axs[0].set_title('Gyroscope sensor values (first 1 minute)')

    accel_activity_data = accel_data.iloc[:300, :][accel_data.iloc[:300, :]['Activity'] == activity]
    sns.lineplot(x='timestamp', y='Value3', data=accel_activity_data, ax=axs[1], label='z-axis')
    axs[1].axhline(y=20, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')

    axs[1].set_title('Accelerometer sensor values (first 1 minute)')

for ax in axs:
    ax.legend(title='Sensor column')
plt.xlabel("Timestamp")
plt.ylabel("Sensor Values")

plt.legend(title="Activity")
plt.show()

# only z axis value seems relevant
plt.figure(figsize=(13, 8))

fig, axs = plt.subplots(1, 2, figsize=(30, 10), sharex='all', sharey='all')

# 300 rows = 60s interval
for activity in gyro_data.iloc[300:600, :]['Activity'].unique():
    activity_data = gyro_data.iloc[300:600, :][gyro_data.iloc[300:600, :]['Activity'] == activity]

    sns.lineplot(x='timestamp', y='Value3', data=activity_data, ax=axs[0], label='z-axis')
    axs[0].axhline(y=20, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
    axs[0].set_title('Gyroscope sensor values (second minute)')

    accel_activity_data = accel_data.iloc[300:600, :][accel_data.iloc[300:600, :]['Activity'] == activity]
    sns.lineplot(x='timestamp', y='Value3', data=accel_activity_data, ax=axs[1], label='z-axis')
    axs[1].axhline(y=20, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
    axs[1].set_title('Accelerometer sensor values (second minute)')

for ax in axs:
    ax.legend(title='Sensor column')
plt.xlabel("Timestamp")
plt.ylabel("Sensor Values")

plt.legend(title="Activity")
plt.show()

# only z axis value seems relevant
plt.figure(figsize=(13, 8))

fig, axs = plt.subplots(1, 2, figsize=(30, 10), sharex='all', sharey='all')

# 300 rows = 60s interval
for activity in gyro_data.iloc[10500:10900, :]['Activity'].unique():
    activity_data = gyro_data.iloc[10500:10900, :][gyro_data.iloc[10500:10900, :]['Activity'] == activity]

    sns.lineplot(x='timestamp', y='Value3', data=activity_data, ax=axs[0], label=activity)
    axs[0].axhline(y=20, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
    axs[0].set_title('Gyroscope sensor values')

    accel_activity_data = accel_data.iloc[10500:10900, :][accel_data.iloc[10500:10900, :]['Activity'] == activity]
    sns.lineplot(x='timestamp', y='Value3', data=accel_activity_data, ax=axs[1], label=activity)
    axs[1].axhline(y=20, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
    axs[1].set_title('Accelerometer sensor values')

for ax in axs:
    ax.legend(title='Sensor column')
plt.xlabel("Timestamp")
plt.ylabel("Sensor Values")

plt.legend(title="Activity")
plt.show()

# only z axis value seems relevant
plt.figure(figsize=(13, 8))

fig, axs = plt.subplots(2, 1, figsize=(30, 10), sharex='all', sharey='all')

# 300 rows = 60s interval
for activity in gyro_data.iloc[:5000, :]['Activity'].unique():
    activity_data = gyro_data.iloc[:5000, :][gyro_data.iloc[:5000, :]['Activity'] == activity]

    sns.lineplot(x='timestamp', y='Value3', data=activity_data, ax=axs[0], label=activity)

    axs[0].set_title('Gyroscope z-axis sensor values')

    accel_activity_data = accel_data.iloc[:5000, :][accel_data.iloc[:5000, :]['Activity'] == activity]
    sns.lineplot(x='timestamp', y='Value3', data=accel_activity_data, ax=axs[1], label=activity)

    axs[1].set_title('Accelerometer z-axis sensor values')

axs[0].axhline(y=17, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
axs[1].axhline(y=16, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
for ax in axs:
    ax.legend(title='Sensor column')
plt.xlabel("Timestamp")
plt.ylabel("Sensor Values")

plt.legend(title="Activity")
plt.show()

len(gyro_data)

import matplotlib.pyplot as plt
import seaborn as sns
# only z axis value seems relevant
plt.figure(figsize=(13, 8))

fig, axs = plt.subplots(2, 1, figsize=(30, 10), sharex='all', sharey='all')

# 300 rows = 60s interval
for activity in gyro_data.iloc[4500:10000, :]['Activity'].unique():
    activity_data = gyro_data.iloc[4500:10000, :][gyro_data.iloc[4500:10000, :]['Activity'] == activity]

    sns.lineplot(x='timestamp', y='Value3', data=activity_data, ax=axs[0], label=activity)

    axs[0].set_title('Gyroscope z-axis sensor values')

    accel_activity_data = accel_data.iloc[4500:10000, :][accel_data.iloc[4500:10000, :]['Activity'] == activity]
    sns.lineplot(x='timestamp', y='Value3', data=accel_activity_data, ax=axs[1], label=activity)

    axs[1].set_title('Accelerometer z-axis sensor values')

axs[0].axhline(y=16, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
axs[1].axhline(y=20, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
for ax in axs:
    ax.legend(title='Sensor column')
plt.xlabel("Timestamp")
plt.ylabel("Sensor Values")

plt.legend(title="Activity")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
# only z axis value seems relevant
plt.figure(figsize=(13, 8))

fig, axs = plt.subplots(2, 1, figsize=(30, 10), sharex='all', sharey='all')

# 300 rows = 60s interval
for activity in gyro_data.iloc[36944:42000, :]['Activity'].unique():
    activity_data = gyro_data.iloc[36944:42000, :][gyro_data.iloc[36944:42000, :]['Activity'] == activity]

    sns.lineplot(x='timestamp', y='Value3', data=activity_data, ax=axs[0], label=activity)

    axs[0].set_title('PERSON 2 Gyroscope z-axis sensor values')

    accel_activity_data = accel_data.iloc[36944:42000, :][accel_data.iloc[36944:42000, :]['Activity'] == activity]
    sns.lineplot(x='timestamp', y='Value3', data=accel_activity_data, ax=axs[1], label=activity)

    axs[1].set_title('PERSON 2 Accelerometer z-axis sensor values')

axs[0].axhline(y=16, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
axs[1].axhline(y=20, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
for ax in axs:
    ax.legend(title='Sensor column')
plt.xlabel("Timestamp")
plt.ylabel("Sensor Values")

plt.legend(title="Activity")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
# only z axis value seems relevant
plt.figure(figsize=(13, 8))

fig, axs = plt.subplots(2, 1, figsize=(30, 10), sharex='all', sharey='all')

# 300 rows = 60s interval
for activity in gyro_data.iloc[42000:47000, :]['Activity'].unique():
    activity_data = gyro_data.iloc[42000:47000, :][gyro_data.iloc[42000:47000, :]['Activity'] == activity]

    sns.lineplot(x='timestamp', y='Value3', data=activity_data, ax=axs[0], label=activity)

    axs[0].set_title('PERSON 2 Gyroscope z-axis sensor values')

    accel_activity_data = accel_data.iloc[42000:47000, :][accel_data.iloc[42000:47000, :]['Activity'] == activity]
    sns.lineplot(x='timestamp', y='Value3', data=accel_activity_data, ax=axs[1], label=activity)

    axs[1].set_title('PERSON 2 Accelerometer z-axis sensor values')

axs[0].axhline(y=16, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
axs[1].axhline(y=20, color='gray', linestyle=':', linewidth=1.5, label=f'Bite Threshold')
for ax in axs:
    ax.legend(title='Sensor column')
plt.xlabel("Timestamp")
plt.ylabel("Sensor Values")

plt.legend(title="Activity")
plt.show()

len(gyro_data)
# print(gyro_data['Activity'])

import numpy as np
import pandas as pd
from scipy.signal import butter, filtfilt
gyro_data_eat = gyro_data[gyro_data['Activity'] == 3]
accel_data_eat = accel_data[accel_data['Activity'] == 3]
# print(len(gyro_data_eat))
# Butterworth Filter to smooth sensor data
def butter_lowpass_filter(data, cutoff=3, fs=50, order=5):
    nyquist = 0.5 * fs
    normal_cutoff = cutoff / nyquist
    b, a = butter(order, normal_cutoff, btype='low', analog=False)
    return filtfilt(b, a, data)

# Preprocess the data (smoothing, normalizing, and segmenting)
def preprocess_sensor_data(df, window_size=50, step_size=25):
    # Apply the low-pass filter
    df['x_filtered'] = butter_lowpass_filter(df['Value1'])
    df['y_filtered'] = butter_lowpass_filter(df['Value2'])
    df['z_filtered'] = butter_lowpass_filter(df['Value3'])

    # Normalize
    for col in ['x_filtered', 'y_filtered', 'z_filtered']:
        df[col] = (df[col] - df[col].mean()) / df[col].std()

    # Segment the data into windows for model input
    segments = []
    for i in range(0, len(df) - window_size, step_size):
        segment = df[['x_filtered', 'y_filtered', 'z_filtered']].iloc[i:i + window_size].values
        segments.append(segment)

    return np.array(segments)

# Sample usage with gyro and accel data
gyro_segments = preprocess_sensor_data(gyro_data_eat)
accel_segments = preprocess_sensor_data(accel_data_eat)

print("Shape of gyro_segments:", gyro_segments.shape)
labels = np.array(labels).flatten()
print("Shape of labels:", labels.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten

# Define the main gesture detection model
def build_model(input_shape):
    model = Sequential([
        Conv1D(64, kernel_size=3, activation='relu', input_shape=input_shape),
        MaxPooling1D(pool_size=2),
        Conv1D(128, kernel_size=3, activation='relu'),
        MaxPooling1D(pool_size=2),
        LSTM(50, return_sequences=False),
        Dense(64, activation='relu'),
        Dense(1, activation='sigmoid')  # Binary classification for eating vs non-eating
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Training the model
model = build_model(input_shape=(50, 3))
model.fit(gyro_segments, labels, epochs=10, validation_split=0.2, batch_size=32)

"""## PLOTS"""

# Separate the data based on the type of IMU sensors
imu_sensors = ['MPL Accelerometer', 'MPL Gyroscope']

# Filter the sensor data for IMU sensors only
imu_data = sensor_data_aligned[sensor_data_aligned['Sensor'].isin(imu_sensors)]

# Plot time series for all activities (for each sensor and its values)
plt.figure(figsize=(6, 4))

for sensor in imu_sensors:
    plt.plot(imu_data[imu_data['Sensor'] == sensor]['timestamp'],
             imu_data[imu_data['Sensor'] == sensor]['Value1'], label=sensor)

plt.xlabel('Timestamp')
plt.ylabel('Ax (Magnitude)')
plt.title('IMU Sensor Values Over Time for All Activities')
plt.legend(loc='upper right')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Ensure the timestamp column is in datetime format if not already
sensor_data_aligned['timestamp'] = pd.to_datetime(sensor_data_aligned['timestamp'])

# Separate the data based on the type of IMU sensors
imu_sensors = ['MPL Accelerometer', 'MPL Gyroscope', 'MPL Rotation Vector', 'MPL Linear Acceleration']
value_columns = ['Value1', 'Value2', 'Value3', 'norm2']
activities = ['eat','talk']
# Filter the sensor data for IMU sensors only
imu_data = sensor_data_aligned[sensor_data_aligned['Sensor'].isin(imu_sensors)]
imu_data = imu_data[imu_data['Activity'].isin(activities)]
# Create subplots for each sensor and value type
fig, axs = plt.subplots(len(imu_sensors), len(value_columns), figsize=(25, 15), sharex='all', sharey='all')

for i, sensor in enumerate(imu_sensors):
    sensor_data = imu_data[imu_data['Sensor'] == sensor]

    for j, value_col in enumerate(value_columns):
        # Plot data with activity labels for each value column
        for activity in sensor_data['Activity'].unique():
            activity_data = sensor_data[sensor_data['Activity'] == activity]
            axs[i, j].plot(activity_data['timestamp'], activity_data[value_col], label=activity)

        axs[i, j].set_title(f'{sensor} - {value_col}')
        axs[i, j].grid(True)
        if i == len(imu_sensors) - 1:
            axs[i, j].set_xlabel('Timestamp')
        if j == 0:
            axs[i, j].set_ylabel(value_col)
        axs[i, j].legend(loc='upper right')
# Adjust layout
# plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

""" Visualizing activity distributuion for person 1 using IMU data (accelerometer and gyroscope) """

# Ensure the timestamp column is in datetime format if not already
sensor_data_aligned['timestamp'] = pd.to_datetime(sensor_data_aligned['timestamp'])

# Separate the data based on the type of IMU sensors
imu_sensors = ['MPL Accelerometer', 'MPL Gyroscope', 'MPL Rotation Vector', 'MPL Linear Acceleration']

# Filter the sensor data for IMU sensors only
imu_data = sensor_data_aligned[sensor_data_aligned['Sensor'].isin(imu_sensors)]

# Create subplots for each sensor
fig, axs = plt.subplots(len(imu_sensors), 1, figsize=(12, 8), sharex=True)

for i, sensor in enumerate(imu_sensors):
    # Filter data for the current sensor
    sensor_data = imu_data[imu_data['Sensor'] == sensor]

    # Plot data with activity labels
    for activity in sensor_data['Activity'].unique():
        activity_data = sensor_data[sensor_data['Activity'] == activity]
        axs[i].plot(activity_data['timestamp'], activity_data['norm2'], label=activity)

    axs[i].set_ylabel('Norm2 (Magnitude)')
    axs[i].set_title(f'{sensor} Data Over Time')
    axs[i].legend(loc='upper right')
    axs[i].grid(True)

axs[-1].set_xlabel('Timestamp')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import seaborn as sns

# Pivot the data for heatmap
heatmap_data = imu_data.pivot_table(index='timestamp', columns=['Sensor', 'Activity'], values='Value1', aggfunc='mean')

plt.figure(figsize=(15, 10))
sns.heatmap(heatmap_data, cmap='viridis', cbar_kws={'label': 'Mean Value1'})
plt.title('Heatmap of Mean Value1 by Sensor and Activity')
plt.xlabel('Sensor and Activity')
plt.ylabel('Timestamp')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 10))
sns.boxplot(x='Activity', y='Value1', hue='Sensor', data=imu_data)
plt.title('Boxplot of Sensor Values by Activity')
plt.xlabel('Activity')
plt.ylabel('Value1')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

sns.pairplot(imu_data, hue='Activity', vars=value_columns)
plt.title('Pair Plot of Sensor Values')
plt.tight_layout()
plt.show()

rolling_window = 10  # Adjust window size as needed

fig, axs = plt.subplots(len(imu_sensors), len(value_columns), figsize=(25, 15), sharex='all', sharey='all')

for i, sensor in enumerate(imu_sensors):
    sensor_data = imu_data[imu_data['Sensor'] == sensor]

    for j, value_col in enumerate(value_columns):
        for activity in sensor_data['Activity'].unique():
            activity_data = sensor_data[sensor_data['Activity'] == activity]
            axs[i, j].plot(activity_data['timestamp'], activity_data[value_col], label=f'{activity} - Raw')
            activity_data[f'{value_col}_rolling'] = activity_data[value_col].rolling(window=rolling_window).mean()
            axs[i, j].plot(activity_data['timestamp'], activity_data[f'{value_col}_rolling'], label=f'{activity} - Rolling Mean', linestyle='--')

        axs[i, j].set_title(f'{sensor} - {value_col}')
        axs[i, j].grid(True)
        if i == len(imu_sensors) - 1:
            axs[i, j].set_xlabel('Timestamp')
        if j == 0:
            axs[i, j].set_ylabel(value_col)
        axs[i, j].legend(loc='upper right')

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Assuming 'Activity' or 'Status' can be categorized
plt.figure(figsize=(12, 6))

# Scatter plot of Acceleration colored by Activity
scatter = plt.scatter(filtered_data['timestamp'], filtered_data['norm2'],
                      c=filtered_data['Activity'].astype('category').cat.codes,
                      cmap='viridis', alpha=0.6)
plt.colorbar(scatter, label='Activity')

# Formatting
plt.xlabel('Timestamp')
plt.ylabel('Acceleration')
plt.title('Linear Acceleration Over Time Colored by Activity')
plt.xticks(rotation=45)
plt.tight_layout()
plt.legend
# Show plot
plt.show()



"""# Graphs"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import skew, kurtosis
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import warnings

# Suppress FutureWarning for interpolation (optional)
warnings.filterwarnings("ignore", category=FutureWarning)

# Define numeric columns and window size
numeric_columns = ['Value1', 'Value2', 'Value3']

# Placeholder to store data from all participants
cumulative_dataset = pd.DataFrame()

# Loop through each participant's data (IDs 1101 to 1138)
for person_id in range(1101, 1139):
    try:
        # Load the CSV files for the current person
        annotations_path = f"./{person_id}/{person_id}_annotate.csv"
        sensor_data_path = f"./{person_id}/{person_id}_sensorData.csv"

        annotations = pd.read_csv(annotations_path)
        sensor_data = pd.read_csv(sensor_data_path)

        # Convert timestamps
        annotations['timestamp'] = pd.to_datetime(annotations['unix time'], unit='ms')
        sensor_data['timestamp'] = pd.to_datetime(sensor_data['Unix Time'], unit='ms')

        # Filter out unwanted sensor (Light sensor)
        sensor_data = sensor_data[sensor_data['Sensor'] != 'LTR-506ALS Light sensor']

        # Resample the sensor data to 200ms intervals
        sensor_data_resampled = (sensor_data
            .set_index('timestamp')
            .groupby('Sensor')[numeric_columns]
            .resample('200ms')
            .mean()
            .reset_index()
        )

        # Ensure numeric columns are properly typed before interpolation
        sensor_data_resampled[numeric_columns] = sensor_data_resampled[numeric_columns].apply(pd.to_numeric, errors='coerce')

        # Sort both DataFrames by timestamp
        sensor_data_resampled = sensor_data_resampled.sort_values('timestamp')
        annotations = annotations.sort_values('timestamp')

        # Merge sensor data with annotations using nearest merge
        sensor_data_aligned = pd.merge_asof(
            sensor_data_resampled,
            annotations[['timestamp', 'Activity']],
            on='timestamp',
            direction='nearest'
        )

        # Add person_id to track the participant
        sensor_data_aligned['person_id'] = person_id

        # Interpolate missing sensor data to fill gaps
        sensor_data_aligned.interpolate(method='linear', inplace=True)

        # Append the current person's data to the cumulative dataset
        cumulative_dataset = pd.concat([cumulative_dataset, sensor_data_aligned], ignore_index=True)

    except FileNotFoundError as e:
        print(f"Data for person {person_id} not found, skipping...")

cumulative_dataset.to_csv(r"./cumulative_sensor_data2.csv", index=False, header=True, encoding='utf-8')

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(20, 6))
sns.countplot(x='Activity', data=cumulative_dataset)
plt.title('Number of Samples by Activity')
plt.show()

# Consolidate and unify activity labels
label_mapping = {
    'computer_work': 'computer',
    'play_cellphone': 'computer',
    'ipad_work': 'computer',
    'computer': 'computer',
    'study': 'study',
    'homework': 'study',
    'home_work': 'study'
}

# Additional label mapping for "Others"
# We'll add any other labels that aren't "computer", "study", "eat", "talk", "drink", "walk", or "stair"
cumulative_dataset['Activity'] = cumulative_dataset['Activity'].replace(label_mapping)

# Define the main activity categories that will stay as they are
main_activities = {'computer', 'study', 'eat', 'talk', 'drink', 'walk', 'stair'}

# Any label not in main_activities will be categorized as "Others"
cumulative_dataset['Activity'] = cumulative_dataset['Activity'].apply(
    lambda x: x if x in main_activities else 'Others'
)

# Verify updated label distribution
# print(cumulative_dataset['Activity'].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(20, 6))
sns.countplot(x='Activity', data=cumulative_dataset)
plt.title('Number of Samples by Activity')
plt.show()

plt.figure(figsize=(25, 8))
sns.countplot(x='person_id', hue='Activity', data=cumulative_dataset)
plt.title('Activities by Users')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Set up Seaborn style for plots
sns.set_style("whitegrid")

# Define specific person and activity to visualize
specific_user = 1110
activity = 'eat'

# Filter dataset for the specific user, activity, and sensors
data_activity = cumulative_dataset[
    (cumulative_dataset['person_id'] == specific_user) &
    (cumulative_dataset['Activity'] == activity) &
    (cumulative_dataset['Sensor'].isin(['MPL Gyroscope', 'MPL Accelerometer']))
]

# Take the first 1000 data points for visualization
data_activity = data_activity

# Print description of the filtered data
print(data_activity.describe())

# Create separate plots for each sensor
sensors = data_activity['Sensor'].unique()
for sensor in sensors:
    sensor_data = data_activity[data_activity['Sensor'] == sensor]

    plt.figure(figsize=(15, 6))
    sns.lineplot(x='timestamp', y='Value1', data=sensor_data, label='Value1 (x-axis)')
    sns.lineplot(x='timestamp', y='Value2', data=sensor_data, label='Value2 (y-axis)')
    sns.lineplot(x='timestamp', y='Value3', data=sensor_data, label='Value3 (z-axis)')

    # Customize plot
    plt.legend(loc="upper right")
    plt.ylabel('Signal Values')
    plt.title(f'{activity.capitalize()} - {sensor} Signal Values Over Time for User {specific_user}')
    plt.xticks(rotation=45)
    plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Set up Seaborn style for plots
sns.set_style("whitegrid")

# Define specific person and activity to visualize
specific_user = 1110
activity = 'talk'

# Filter dataset for the specific user, activity, and sensors
data_activity = cumulative_dataset[
    (cumulative_dataset['person_id'] == specific_user) &
    (cumulative_dataset['Activity'] == activity) &
    (cumulative_dataset['Sensor'].isin(['MPL Gyroscope', 'MPL Accelerometer']))
]

# Take the first 1000 data points for visualization
data_activity = data_activity

# Print description of the filtered data
print(data_activity.describe())

# Create separate plots for each sensor
sensors = data_activity['Sensor'].unique()
for sensor in sensors:
    sensor_data = data_activity[data_activity['Sensor'] == sensor]

    plt.figure(figsize=(15, 6))
    # sns.lineplot(x='timestamp', y='Value1', data=sensor_data, label='Value1 (x-axis)')
    # sns.lineplot(x='timestamp', y='Value2', data=sensor_data, label='Value2 (y-axis)')
    sns.lineplot(x='timestamp', y='Value3', data=sensor_data, label='Value3 (z-axis)')

    # Customize plot
    plt.legend(loc="upper right")
    plt.ylabel('Signal Values')
    plt.title(f'{activity.capitalize()} - {sensor} Signal Values Over Time for User {specific_user}')
    plt.xticks(rotation=45)
    plt.show()
